# 05.2-迭代器与生成器-Generator

## 一 理解生成器

### 1.1 创建生成器

Generator 是 ES6 提供的一种异步编程解决方案，拥有能力：**在一个函数块内暂停、恢复代码的执行**。

生成器的形式是一个函数，函数名称前面加一个星号表示它是一个生成器，只要是可以定义函数的地方，就可以定义生成器：

```js
// 生成器函数声明
function* generatorFn() {}
// 生成器函数表达式
let generatorFn = function* () {}
// 作为对象字面量方法的生成器函数
let foo = {
  *generatorFn() {},
}
// 作为类实例方法的生成器函数
class Foo {
  *generatorFn() {}
}
// 作为类静态方法的生成器函数
class Bar {
  static *generatorFn() {}
}
```

贴士：箭头函数不能用来定义生成器函数，标识生成器的星号不受空格位置的影响。

### 1.2 生成器执行原理

生成器的语法行为与传统函数完全不同，其原理是其内部被包装成了迭代器（实现了 Iterator 接口），利用 next() 的方式调用：

```js
function* gen() {
  console.log('hello world!')
}

// 调用生成器函数会产生一个生成器对象,生成器对象一开始处于暂停执行（ suspended）的状态
let iter = gen()
console.log(iter) // Object [Generator] {}

iter.next() // hello world!
iter.next() // 空
```

next()方法的返回值类似于迭代器，有一个 done 属性和一个 value 属性。函数体为空的生成器函数中间不会停留，调用一次 next()就会让生成器到达 done: true 状态。

```js
function* generatorFn() {}
let generatorObject = generatorFn()
console.log(generatorObject) // generatorFn {<suspended>}
console.log(generatorObject.next()) // { done: true, value: undefined }
```

value 属性是生成器函数的返回值，默认值为 undefined，可以通过生成器函数的返回值指定：

```js
function* generatorFn() {
  return 'foo'
}
let generatorObject = generatorFn()
console.log(generatorObject) // generatorFn {<suspended>}
console.log(generatorObject.next()) // { done: true, value: 'foo' }
```

### 1.3 yeild 语句

生成器最重要的地方是：可以通过 yeild 关键字让生成器开始、停止执行！生成器函数在遇到 yield 之前会正常执行，遇到该关键字则停止执行，函数的作用域状态会被保留，重新调用 next() 之后可以恢复执行！停止执行的生成器函数只能通过在生成器对象上调用 next()方法来恢复执行!

`yeild` 语句可以看做函数代码的分隔符，将函数拆分成了多个部分，每个 `yeild` 将会由一个 next 执行：

```js
function* gen() {
  console.log('hello world!')
  yield 'hello 1'
  yield
  yield 'hello 3'
  return 'world'
}

let y = gen()

console.log(y.next()) // hello world! { value: 'hello 1', done: false }
console.log(y.next()) // { value: undefined, done: false }
console.log(y.next()) // { value: 'hello 3', done: false }
console.log(y.next()) // { value: 'world', done: true }
console.log(y.next()) // { value: undefined, done: true }
```

yield 关键字有点像函数的中间返回语句，它生成的值会出现在 next() 方法返回的对象里，通过 yield 关键字退出的生成器函数会处在 done: false 状态；通过 return 关键字退出的生成器函数会处于 done: true 状态。

贴士：

- 生成器函数内部的执行流程会针对每个生成器对象区分作用域。在一个生成器对象上调用 next() 不会影响其他生成器的。
- yield 关键字只能在生成器函数内使用

### 1.4 与 Iterator 接口的关系

生成器对象实现了 Iterable 接口，它们默认的迭代器是自引用的：

```js
function* generatorFn() {}
console.log(generatorFn) // f* generatorFn() {}

console.log(generatorFn()[Symbol.iterator]) // f [Symbol.iterator]() {native code}

console.log(generatorFn()) // generatorFn {<suspended>}

console.log(generatorFn()[Symbol.iterator]()) // generatorFn {<suspended>}

const g = generatorFn()
console.log(g === g[Symbol.iterator]()) // true
```

Generator 函数就是遍历器生成函数，因此可以把 Generator 赋值给对象的 Symbol.iterator 属性，从而使得该对象具有 Iterator 接口：

```js
const myIterabel = {}

myIterabel[Symbol.iterator] = function* () {
  yield 1
  yield 2
  yield 3
}

console.log([...myIterabel]) // 11 (1 , 2 , 3]
```

### 1.5 next() 方法参数

yield 语句本身没有返回值，或者说总是返回 undefined。next 方法可以带有一个参数，该参数会被当作上一条 yield 语句的返回值：

```js
function* f() {
  for (let i = 0; true; i++) {
    let res = yield i
    console.log('res = ', res)
    if (res) {
      i = -1
    }
  }
}

const g = f()
console.log(g.next()) //  res = undefined { value: 0, done: false }
console.log(g.next()) //  res = undefined  { value: 1, done: false }
console.log(g.next(true)) // { value: 0, done: false }  // res为真，下一轮循环从 -1 开始递增
```

这个功能有很重要的语法意义：Generator 函数从暂停状态到恢复运行，其上下文状态(context)是不变的。 通过 next 方法的参数就有办法在 Generator 函数开始运行后继续向函数体内部注入值 。 也就是说，可以在 Generator 函数运行的不同阶段从外部向内部注入不同的值，从而调整函数行为。

贴士：由 于 next 方法的参数表示上一条 yield 语句的返回值， 所以第一次使用 next 方法时传递参数是无效的。 V8 引擎直接忽略第一次使用 next 方法时的参数，只有从第二次使用 next 方法开始，参数才是有效的。从语义上讲，第一个 next 方法用来启动追历器对象，所以不用带有参数。

如果想要在第一次调用 next 方法时就能够输入值，可以在 Generator 函数外面再包一层：

```js
function wrapper(generatorFn) {
  return function (...args) {
    let generatorObj = generatorFn(...args)
    generatorObj.next()
    return generatorObj
  }
}

const wrapped = wrapper(function* () {
  return 'DONE'
})

console.log(wrapped().next('hi')) // { value: undefined, done: true }
```

上面的代码中， Generator 函数如果不用 wrapper 先包一层，是无法在第一次调用 next 方法时就输入参数的。最后一个示例：

```js
function* dataConsumer() {
  console.log('started')
  console.log(`1. ${yield}`)
  console.log(`2. ${yield}`)
  return 'result'
}

let genObj = dataConsumer()
genObj.next() // started
genObj.next('a') // 1. a
genObj.next('b') // 1. b
```

### 1.6 for..of 遍历迭代器对象

for...of 循环可以自动遍历 Generator 函数生成的 Iterator 对象，且此时不再需要调用 next 方法：

```js
function* foo() {
  yield l
  yield 2
  yield 3
  yield 4
  yield 5
  return 6
}
for (let v of foo()) {
  console.log(v) // 1 2 3 4 5
}
```

利用 Generator 函数和 for...of 循环实现斐波那契数列：

```js
function* fibonacci() {
  let [prev, curr] = [0, 1]
  for (;;) {
    ;[prev, curr] = [curr, prev + curr]
    yield curr
  }
}

for (let n of fibonacci()) {
  if (n > 1000) {
    break
  }
  console.log(n)
}
```

原生的 JavaScript 对象没有遍历接口，无法直接使用 for...of 循环，通过 Generator 函数为它加上这个接口后就可以用了。有两种方案。

方案一：

```js
function* objectEntries(obj) {
  let propKeys = Reflect.ownKeys(obj)
  for (let propKey of propKeys) {
    yield [propKey, obj[propKey]]
  }
}

let jane = { first: 'Jane', last: 'Doe' }
for (let [key, value] of objectEntries(jane)) {
  // first: Jane
  // last: Doe
  console.log(`${key}: ${value}`)
}
```

方案二：将 Generator 函数加到对象的 Symbol . iterator 属性上

```js
function* objectEntries(obj) {
  let propKeys = Object.keys(this)
  for (let propKey of propKeys) {
    yield [propKey, obj[propKey]]
  }
}

let jane = { first: 'Jane', last: 'Doe' }

jane[Symbol.iterator] = objectEntries

for (let [key, value] of objectEntries(jane)) {
  // first: Jane
  // last: Doe
  console.log(`${key}: ${value}`)
}
```

贴士：除了 for ... of 循环 ，扩展运算符（．．．）、解构赋值和 Array.from 方法内部调用的都是迭代器接口。这意味着 ，它们都可以将 Generator 函数返回的 Iterator 对象作为参数。

## 二 生成器的使用

### 2.1 生成器对象作为可迭代对象

在生成器对象上显式调用 next()方法的用处并不大。其实，如果把生成器对象当成可迭代对象，那么使用起来会更方便：

```js
function* generatorFn() {
  yield 1
  yield 2
  yield 3
}

for (const x of generatorFn()) {
  console.log(x) // 1 2 3
}
```

在需要自定义迭代对象时，这样使用生成器对象会特别有用。比如，我们需要定义一个可迭代对象，而它会产生一个迭代器，这个迭代器会执行指定的次数。使用生成器，可以通过一个简单的循环来实现：

```js
function* nTimes(n) {
  while (n--) {
    yield
  }
}

for (let _ of nTimes(3)) {
  console.log('foo')
}
```

### 2.2 使用 yield 实现输入和输出

除了可以作为函数的中间返回语句使用， yield 关键字还可以作为函数的中间参数使用。上一次让生成器函数暂停的 yield 关键字会接收到传给 next()方法的第一个值。这里有个地方不太好理解——第一次调用 next()传入的值不会被使用，因为这一次调用是为了开始执行生成器函数：

```js
function* generatorFn(initial) {
  console.log(initial)
  console.log(yield)
  console.log(yield)
}

let generatorObject = generatorFn('foo')
generatorObject.next('bar') // foo
generatorObject.next('baz') // baz
generatorObject.next('qux') // qux
```

yield 关键字可以同时用于输入和输出，如下例所示：

```js
function* generatorFn() {
  return yield 'foo'
}
let generatorObject = generatorFn()
console.log(generatorObject.next()) // { done: false, value: 'foo' }
console.log(generatorObject.next('bar')) // { done: true, value: 'bar' }
```

因为函数必须对整个表达式求值才能确定要返回的值，所以它在遇到 yield 关键字时暂停执行并计算出要产生的值： "foo"。下一次调用 next()传入"bar"，作为交给同一个 yield 的值。然后这个值被确定为本次生成器函数要返回的值。yield 关键字并非只能使用一次。比如，以下代码就定义了一个无穷计数生成器函数：

```js
function* generatorFn() {
  for (let i = 0; ; ++i) {
    yield i
  }
}

let generatorObject = generatorFn()
console.log(generatorObject.next().value) // 0
console.log(generatorObject.next().value) // 1
console.log(generatorObject.next().value) // 2
console.log(generatorObject.next().value) // 3
console.log(generatorObject.next().value) // 4
console.log(generatorObject.next().value) // 5
// ...
```

假设我们想定义一个生成器函数，它会根据配置的值迭代相应次数并产生迭代的索引。初始化一个新数组可以实现这个需求，但不用数组也可以实现同样的行为：

```js
function* nTimes(n) {
  for (let i = 0; i < n; ++i) {
    yield i
  }
}
for (let x of nTimes(3)) {
  console.log(x)
}
```

另外，使用 while 循环也可以，而且代码稍微简洁一点：

```js
function* nTimes(n) {
  let i = 0
  while (n--) {
    yield i++
  }
}
for (let x of nTimes(3)) {
  console.log(x) // 0 1 2
}
```

这样使用生成器也可以实现范围和填充数组：

```js
function* range(start, end) {
  while (end > start) {
    yield start++
  }
}
for (const x of range(4, 7)) {
  console.log(x) // 4 5 6
}

function* zeroes(n) {
  while (n--) {
    yield 0
  }
}
console.log(Array.from(zeroes(8))) // [0, 0, 0, 0, 0, 0, 0, 0]
```

### 2.3 产生可迭代对象

可以使用星号增强 yield 的行为，让它能够迭代一个可迭代对象，从而一次产出一个值：

```js
// 等价的 generatorFn：
// function* generatorFn() {
//  for (const x of [1, 2, 3]) {
//    yield x;
//  }
// }
function* generatorFn() {
  yield* [1, 2, 3]
}
let generatorObject = generatorFn()
for (const x of generatorFn()) {
  console.log(x) // 1 2 3
}
```

贴士：yield 星号两侧的空格不影响其行为。

因为 `yield*` 实际上只是将一个可迭代对象序列化为一连串可以单独产出的值，所以这跟把 yield 放到一个循环里没什么不同。下面两个生成器函数的行为是等价的：

```js
function* generatorFnA() {
  for (const x of [1, 2, 3]) {
    yield x
  }
}
for (const x of generatorFnA()) {
  console.log(x) // 1 2 3
}

function* generatorFnB() {
  yield* [1, 2, 3]
}
for (const x of generatorFnB()) {
  console.log(x) // 1 2 3
}
```

`yield*` 的值是关联迭代器返回 done: true 时的 value 属性。对于普通迭代器来说，这个值是 undefined：

```js
function* generatorFn() {
  console.log('iter value:', yield* [1, 2, 3])
}
for (const x of generatorFn()) {
  console.log('value:', x) // value: 1  value: 2  value: 3  iter value: undefined
}
```

对于生成器函数产生的迭代器来说，这个值就是生成器函数返回的值：

```js
function* innerGeneratorFn() {
  yield 'foo'
  return 'bar'
}
function* outerGeneratorFn(genObj) {
  console.log('iter value:', yield* innerGeneratorFn())
}
for (const x of outerGeneratorFn()) {
  console.log('value:', x) // value: foo iter value: bar
}
```

### 2.4 生成器作为默认迭代器

因为生成器对象实现了 Iterable 接口，而且生成器函数和默认迭代器被调用之后都产生迭代器，所以生成器格外适合作为默认迭代器。下面是一个简单的例子，这个类的默认迭代器可以用一行代码产出类的内容：

```js
class Foo {
  constructor() {
    this.values = [1, 2, 3]
  }

  *[Symbol.iterator]() {
    yield* this.values
  }
}

// for-of 循环调用了默认迭代器（它恰好又是一个生成器函数）并产生了一个生成器对象。这个生成器对象是可迭代的，所以完全可以在迭代中使用。
const f = new Foo()
for (const x of f) {
  console.log(x) // 1 2 3
}
```

### 2.5 生成器提前终止

与迭代器类似，生成器也支持“可关闭”的概念。一个实现 Iterator 接口的对象一定有 next() 方法，还有一个可选的 return() 方法用于提前终止迭代器。生成器对象除了有这两个方法，还有第三个方法：throw()。

```js
function* generatorFn() {}
const g = generatorFn()
console.log(g) // generatorFn {<suspended>}
console.log(g.next) // f next() { [native code] }
console.log(g.return) // f return() { [native code] }
console.log(g.throw) // f throw() { [native code] }
```

return() 和 throw() 方法都可以用于强制生成器进入关闭状态：

```js
function* generatorFn() {
  for (const x of [1, 2, 3]) {
    yield x
  }
}
const g = generatorFn()
console.log(g) // generatorFn {<suspended>}
console.log(g.return(4)) // { done: true, value: 4 }
console.log(g) // generatorFn {<closed>}
```

与迭代器不同，所有生成器对象都有 return() 方法，只要通过它进入关闭状态，就无法恢复了。后续调用 next() 会显示 done: true 状态，而提供的任何返回值都不会被存储或传播：

```js
function* generatorFn() {
  for (const x of [1, 2, 3]) {
    yield x
  }
}

const g = generatorFn()
console.log(g.next()) // { done: false, value: 1 }
console.log(g.return(4)) // { done: true, value: 4 }
console.log(g.next()) // { done: true, value: undefined }
console.log(g.next()) // { done: true, value: undefined }
console.log(g.next()) // { done: true, value: undefined }
```

for-of 循环等内置语言结构会忽略状态为 done: true 的 IteratorObject 内部返回的值。

throw() 方法会在暂停的时候将一个提供的错误注入到生成器对象中。如果错误未被处理，生成器就会关闭：

```js
function* generatorFn() {
  for (const x of [1, 2, 3]) {
    yield x
  }
}
const g = generatorFn()
console.log(g) // generatorFn {<suspended>}
try {
  g.throw('foo')
} catch (e) {
  console.log(e) // foo
}
console.log(g) // generatorFn {<closed>}
```

不过，假如生成器函数内部处理了这个错误，那么生成器就不会关闭，而且还可以恢复执行。错误处理会跳过对应的 yield，因此在这个例子中会跳过一个值。比如：

```js
function* generatorFn() {
  for (const x of [1, 2, 3]) {
    try {
      yield x
    } catch (e) {}
  }
}

const g = generatorFn()
console.log(g.next()) // { done: false, value: 1}
g.throw('foo')
console.log(g.next()) // { done: false, value: 3}
```

### 2.6 Generator.prototype.throw()

Generator 函数返回的遍历器对象都有一个 throw 方法，可以在函数外部抛出错误，然后在 Generator 函数体内捕获 。

```js
const g = function* () {
  try {
    yield
  } catch (e) {
    console.log('捕获内部错误:', e)
  }
}

let i = g()
i.next()

try {
  i.throw('a')
  i.throw('b')
} catch (e) {
  console.log('捕获外部错误:', e)
}

// 内部捕获 a
// 外部捕获 b
```

上面的代码中，遍历器对象 i 连续抛出两个错误 。 第一个错误被 Generator 函数体内的 catch 语句捕获 。 i 第二次抛出错误，由于 Generator 函数内部的 catch 语句已经执行过了，不会再捕捉到这个错误了，所以这个错误就被抛出了 Generator 函数体，被函数体外的 catch 语句捕获。

throw 方法可以接受一个参数，该参数会被 catch 语句接收，建议抛出 Error 对象的实例：

```js
const g = function* () {
  try {
    yield
  } catch (e) {
    console.log(e)
  }
}

let i = g()
i.next()
i.throw('出错嘞')

// 出错嘞
```

贴士：不要混淆遍历器对象的 throw 方法和全局的 throw 命令 。上面的错误是用遥历器对象的 throw 方法抛出的，而不是用 throw 命令抛出的 。 后者只能被函数体外的 catch 语句捕获。

如果 Generator 函数内部没有部署 try ... catch 代码块，那么 throw 方法抛出的错误将被外部 try ... catch 代码块捕获。

```js
const g = function* () {
  while (true) {
    yield
    console.log('捕获内部错误:', e)
  }
}

let i = g()
i.next()
try {
  throw new Error('a')
} catch (e) {
  console.log('捕获外部错误:', e)
}
```

如果 Generator 函数内部部署了 try . . . catch 代码块，那么遍历器的 throw 方法抛出的错误不影响下一次遍历，否则遍历直接终止。

```js
const gen = function* () {
  yield console.log('hello')
  yield console.log('world')
}

let g = gen()
g.next()
g.throw()
```

上面的代码中， g.throw 抛出错误以后，没有任何 try ... catch 代码块可以捕获这个错误，导致程序报错，中断执行 。

throw 方法被捕获以后会附带执行下一条 yield 表达式，即附带执行一次 next 方法：

```js
const gen = function* () {
  try {
    yield console.log('a')
  } catch (e) {}
  yield console.log('b')
  yield console.log('c')
}

let g = gen()
g.next() // a
g.throw() // b
g.next() // c
```

上面的代码中， g .th row 方法被捕获以后会自动执行一次 next 方法，所以打印 b 。 另外，也可以看到，只要 Generator 函数内部部署了 try ... catch 代码块，那么遍历器的 throw 方法抛出的错误便不会影响下一次遍历 。

另外， throw 命令与 g . throw 方法是无关的，两者互不影响：

```js
const gen = function* () {
  yield console.log('hello')
  yield console.log('world')
}

let g = gen()
g.next()

try {
  throw new Error()
} catch (e) {
  g.next()
}
```

上面的代码中， throw 命令抛出的错误不会影响到遍历器的状态，所以两次执行 next 方法都完成了正确的操作。

这种函数体内捕获错误的机制大大方便了对错误的处理。对于多个 yield 表达式，可以只用 一个 try . . . catch 代码块来捕获错误。如果使用回调函数的写法想要捕获多个错误，就不得不每个函数写 ← 个错误处理语句，而现在只在 Generator 函数内部写一次 catch 语句就可以了。

Generator 函数体外抛出的错误可以在函数体内捕获：反过来， Generator 函数体内抛出的错误也可以被函数体外的 catch 捕获。

```js
function* foo() {
  let x = yield 3
  let y = x.toUpperCase()
  yield y
}

let it = foo()

it.next() // {value: 3, done: false}

try {
  it.next(42)
} catch (e) {
  console.log(e)
}
```

上面的代码中，第二个口 ext 方法向函数体内传入一个参数 42 ，数值是没有 toUpperCase 方法的，所以会抛出一个 TypeError 错误，被函数体外的 catch 捕获 。

一旦 Generator 执行过程中抛出错误，就不会再执行下去了 。 如果此后还调用 next 方法，将返回一个 value 属性等于 undefined 、 done 属性等于 true 的对象，即 JavaScript 引擎认为这个 Generator 己经运行结束。

### 2.7 Generator.prototype.return()

return 方法，可以返回给定的值，并终结 Generator 函数的遍历。

```js
function* gen() {
  yield 1
  yield 2
  yield 3
}

let g = gen()

g.next()
g.return('foo')
g.next()
```

上面的代码中，遍历器对象 q 调用 return 方法后，返回值的 value 属性就是 return 方法的参数 foo 。同时， Generator 函数的遍历终止，返回值的 done 属性为 true ，以后再调用 next 方法， done 属性总是返回 true 。

如果 return 方法调用时不提供参数，则返回值的 vaule 属性为 undefined 。

```js
function* gen() {
  yield 1
  yield 2
  yield 3
}

let g = gen()

g.next()
g.return()
```

如果 Generator 函数内部有 try . .. finally 代码块，那么 return 方法会推迟到 finally 代码块执行完再执行。

```js
function* numbers() {
  yield 1
  try {
    yield 2
    yield 3
  } finally {
    yield 4
    yield 5
  }
  yield 6
}

let g = numbers()
g.next()
g.next()
g.return(7)
g.next()
g.next()
```

上面的代码中，调用 return 方法后就开始执行 finally 代码块，然后等到 finally 代码块执行完再执行 return 方法。

### 2.8 yield＊表达式

如果在 Generator 函数内部调用另一个 Generator 函数，默认情况下是没有效果的：

```js
function* foo() {
  yield 'a'
  yield 'b'
}

function* bar() {
  yield 'x'
  foo()
  yield 'y'
}

for (let v of bar()) {
  console.log(v)
}
```

上面的代码中， foo 和 bar 都是 Generator 函数 ， 在 bar 里面调用 foo 是不会有效果的。这时就需要用到 yield＊语句，用来在一个 Generator 函数里面执行另 一个 Generator 函数。

```js
function* bar() {
  yield 'x'
  yield* foo()
  yield 'y'
}

// 等同于
// function* bar() {
//     yield 'x'
//     yield 'a'
//     yield 'b'
//     yield 'y'
// }

// 等同于
// function* bar() {
//     yield 'x'
//     for(let v of foo()){
//         yield v
//     }
//     yield 'y'
// }
```

从语法角度看，如果 yield 命令后面跟的是一个遍历器对象，那么需要在 yield 命令后面加上星号，表明返回的是一个遍历器对象。这被称为 yield 叫吾句。

```js
let deletgatedIterator = (function* () {
  yield 'hello'
  yield 'bye'
})()

let delegatingIterator = (function* () {
  yield 'greetings'
  yield* deletgatedIterator
  yield 'ok, bye'
})()

for (let value of delegatingIterator) {
  console.log(value)
}
```

上面的代码中， delegatingiterator 是代理者， delegatediterator 是被代理者 。由于 yield\* delegatediterator 语句得到的值是一个遍历器，所以要用星号表示。运行结果就是使用一个遍历器遍历了多个 Generator 函数，有递归的效果 。

yield ＊后面的 Generator 函数（没有 return 语句时）等同于在 Generator 函数内部部署一个 for...of 循环。

```js
function* concat(iter1, iter2) {
  yield* iter1
  yield* iter2
}

// 等同于
function* concat(iter1, iter2) {
  for (let value of iter1) {
    yield value
  }

  for (let value of iter2) {
    yield value
  }
}
```

上面的代码说明， yield 食后面的 Generator 函数（没有 return i 吾句时）不过是 f or ... of 的一种简写形式，完全可以用后者替代。反之，在有 return i 吾句时则需要用 `var value = yield` iterator 的形式获取 return 语句的值。

如果 yield＊后面跟着一个数组，由于数组原生支持遍历器，因此就会遍历数组成员 。

```js
function* gen() {
  yield* ['a','b','c'];
}

gen() . next () / / { value :”a ”, done:false }
```

上面的代码中， yield 命令后面如果不加星号，返回的是整个数组，加了 星号就表示返回的是数组的遍历器对象。

实际上，任何数据结构只要有 Iterator 接口，就可以被 yield＊遍历 。

```js
let read = (function* () {
  yield 'hello'
  yield* 'hello'
})()

read.next().value // ” hello ”
read.next().value // ” h ”
```

上面的代码中 ， y i eld 语句返回整个字符串 ， yield＊语句返回单个字符。因为字符串具有 Iterator 接口，所以用 yi eld＊遍历。

如果被代理的 Generator 函数有 return 语句，那么便可以向代理它的 Generator 函数返回数据。

```js
function* foo() {
  yield 2
  yield 3
  return 'foo'
}

function* bar() {
  yield 1
  let v = yield* foo()
  console.log('v: ', v)
  yield 4
}

let it = bar()

it.next()
it.next()
it.next()
it.next()
it.next()
```

在上面的代码第四次调用 next 方法时，屏幕上会有输出 ， 这是因为函数 foo 的 return 语句向函数 bar 提供了返回值 。

```js
function* genFuncWithReturn() {
  yield 'a'
  yield 'b'
  return 'The result'
}
function* logReturned(genObj) {
  let result = yield* genObj
  console.log(result)
}
;[...logReturned(genFuncWithReturn())]
```

上面的代码中 ， 存在两次遍历。第一次是扩展运算符遍历函数 logReturned 返回的遍历器对象 ， 第二次是 yield＊ 语句遍历函数 genFuncWithReturn 返回的遍历器对象 。 这两次遍历的效果是叠加的，最终表现为扩展运算符遍历函数 genFuncWithReturn 返回的遍历器对象 。 所以，最后的数据表达式得到的值等于［ 'a'，'b' ］。 但是，函数 genFuncWithReturn 的 return 语句的返回值 The result 会返回给函数 logReturned 内部的 result 变量 ，因此会有终端输出 。

yield \*命令可以很方便地取出嵌套数组的所有成员 。

```js
function* iterTree(tree) {
  if (Array.isArray(tree)) {
    for (let i = 0; i < tree.length; i++) {
      yield* iterTree(tree[i])
    }
  } else {
    yield tree
  }
}

const tree = ['a', ['b', 'c'], ['d', 'e']]

for (let x of iterTree(tree)) {
  console.log(x)
}
```

### 2.9 作为对象属性的 Generator 函数

如果一个对象的属性是 Generator 函数，那么可以简写成下面的形式：

```js
let obj = {
  *fn() {},
}
```

### 2.10 Generator 函数 this

Generator 函数总是返回 一个遍历器 ， ES6 规定这个遍历器是 G enerator 函数的实例 ，它也继承了 Generator 函数的 prototype 对象上的方法。

```js
function* g() {}
g.prototype.hello = function () {
  return 'hi'
}

let obj = g()
obj instanceof g // true
obj.hello() // hi
```

上面的代码表明， Generator 函数 q 返回的遍历器 obj 是 q 的实例，而且继承了 g.prototype 。但是，如果把 q 当作普通的构造函数，则并不会生效，因为 q 返回的总是遍历器对象，而不是 this 对象。

```js
function* g() {
  this.a = 11
}

let obj = g()
// obj.a // undefined
```

Generator 函数使用 new 命令创建实例！
